version: 2
jobs:
  build:
    working_directory: ~/micropost
    docker:
      - image: cimg/php:7.4.12-node
        environment:
          APP_ENV: test
          DATABASE_URL: mysql://root@127.0.0.1:3306/micro-post
          MAILER_FROM: micro@micropost.com
          MAILER_URL: null://localhost
      - image: circleci/mysql:8.0.4
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: micro-post
    steps:
      - checkout
      - run:
          name: Wait for MySQL
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run:
          name: Update Composer
          command: sudo composer self-update
      - run:
          name: Install Dependencies - Composer install
          command: composer install -n --prefer-dist
      - run:
          name: Clear cache
          command: php bin/console cache:clear --env=test --no-interaction
      - run:
          name: Run migrations
          command: php bin/console doctrine:migrations:migrate --env=test --no-interaction
      - run:
          name: Run tests
          command: ./bin/phpunit
  deploy:
    working_directory: ~/micropost
    docker:
      - image: cimg/php:7.4.12-node
    steps:
      - checkout
      - run:
          name: Install Dependencies - Composer install
          command: composer install -n --prefer-dist
      - run:
          name: Clear cache
          command: php bin/console cache:clear --env=prod --no-interaction
      - run:
          name: Yarn - build front-end dependencies
          command: yarn install && yarn run encore production
      - run:
          name: Install rsync
          command: sudo apt update && sudo apt install rsync
      - run:
          name: Add droplet
          command: ssh-keyscan -H $DROPLET_IP >> ~/.ssh/known_host
      - run:
          name: Pre-deploy
          command: ssh -T -o "StrictHostKeyChecking no" $DROPLET_USER@$DROPLET_IP < bin/deploy/pre_deploy.sh
      - run:
          name: Deploy
          command: rsync -vzcrSLhp --delete ~/micropost/ $DROPLET_USER@$DROPLET_IP:/var/www/micropost_current/
      - run:
          name: Post-deploy
          command: ssh -T -o "StrictHostKeyChecking no" $DROPLET_USER@$DROPLET_IP < bin/deploy/deploy.sh
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master