<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYz7PwZB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYz7PwZB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYz7PwZB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYz7PwZB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYz7PwZB\App_KernelDevDebugContainer([
    'container.build_hash' => 'Yz7PwZB',
    'container.build_id' => 'bf7a0661',
    'container.build_time' => 1604777752,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYz7PwZB');
